version: 2
reverse_providers:
    - id: d2f694a9-09bb-49aa-9cc9-45a15c82f4ca
      server_url: ws://127.0.0.1:3000
      local_host: 127.0.0.1
      local_port: 3306
      api_key: dev-key-one
      channel_id: 0e48a13d-8875-43af-85af-b6db5705d08e
      enabled: true
reverse_consumers:
    - id: 0e48a13d-8875-43af-85af-b6db5705d08e
      listen: 127.0.0.1:10808
      server_url: ws://127.0.0.1:3000
      api_key: dev-key-one
      enabled: true
